[workspace.package]
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
default-members = ["crates/cli"]
members = ["crates/cli", "crates/ndhcp"]

[workspace.dependencies]
clap = { version = "4.5.38", features = ["derive"] }
derive_more = { version = "2.0.1", features = ["display"] }
hyper = { version = "1.6.0", features = ["client", "http1"] }
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.140"
local-ip-address = "0.6.5"
pnet = "0.35.0"
anyhow = "1.0.98"
reqwest = "0.12.15"

[workspace.lints]
