[package]
name = "cli"
version.workspace = true
edition.workspace = true

[[bin]]
name = "fckloud"
path = "src/main.rs"

[dependencies]
clap.workspace = true
pnet.workspace = true
local-ip-address.workspace = true
tokio.workspace = true
tracing.workspace = true
anyhow.workspace = true
tracing-subscriber.workspace = true
time.workspace = true

ndhcp = { path = "../ndhcp" }
kubem = { path = "../kubem" }